server:
  port: 8083

spring:
  application:
    name: item-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/campus_trade

jwt:
  secret: campusTradeSecretKeyCampusTradeSecretKey123456

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - http://localhost:5173
      - http://127.0.0.1:5173
  location:
    request-timeout: 3s
    amap:
      base-url: https://restapi.amap.com
      key: d027d7437e22c3e0ff369249bde56e21
